CREATE DATABASE GSCodeChallenge
GO

USE GSCodeChallenge
GO

CREATE TABLE [User](
	Id	INT IDENTITY(1,1) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([Id])
)
GO


CREATE TABLE [Project](
	Id	INT IDENTITY(1,1) NOT NULL,
	StartDate DATETIME NOT NULL,
	EndDate DATETIME NOT NULL,
	Credits INT NOT NULL,
	CONSTRAINT [PK_Project] PRIMARY KEY CLUSTERED ([Id])
)
GO

CREATE TABLE [UserProject](
	Id	INT IDENTITY(1,1) NOT NULL,
	UserId INT NOT NULL,
	ProjectId INT NOT NULL,
	IsActive BIT NOT NULL,
	AssignedDate DATETIME NOT NULL,
	CONSTRAINT [PK_UserProject] PRIMARY KEY CLUSTERED ([Id]),
	CONSTRAINT [FK_UserProject_User] FOREIGN KEY([UserId]) REFERENCES [User]([Id]),
	CONSTRAINT [FK_UserProject_Project] FOREIGN KEY([ProjectId]) REFERENCES [Project]([Id])
)
GO

USE GSCodeChallenge
GO
CREATE LOGIN GSUser 
    WITH PASSWORD    = N'testPassword',
	DEFAULT_DATABASE = [GSCodeChallenge],
    CHECK_POLICY     = OFF,
    CHECK_EXPIRATION = OFF;
GO
CREATE USER [GSUser] FOR LOGIN [GSUser]
GO
ALTER ROLE [db_owner] ADD MEMBER [GSUser]
GO